# CELERY BUILD

steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Celery-App-Build
  args: ['build', '-f', 'Dockerfile.celery', '-t', 'gcr.io/${PROJECT_ID}/celery-app:$TAG_NAME', '.']

- name: 'gcr.io/cloud-builders/docker'
  id: Celery-App-Push
  args: ['push', 'gcr.io/${PROJECT_ID}/celery-app:$TAG_NAME']