FROM nginx:alpine

RUN mkdir -p /etc/nginx/ssl/
COPY ssl/devdock.work.gd.cer /etc/nginx/ssl/devdock.work.gd.cer
COPY ssl/devdock.work.gd.key /etc/nginx/ssl/devdock.work.gd.key

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
