# NGINX BUILD

steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Nginx-App-Build
  args: ['build', '-f', 'Dockerfile.ssl', '-t', 'gcr.io/${PROJECT_ID}/ssl-app-release:$TAG_NAME', '.']

- name: 'gcr.io/cloud-builders/docker'
  id: Nginx-App-Push
  args: ['push', 'gcr.io/${PROJECT_ID}/ssl-app-release:$TAG_NAME']