apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-deployment
  labels:
    app: ssl-app
spec:
  selector:
    matchLabels:
      app: ssl-app
  template:
    metadata:
      labels:
        app: ssl-app
    spec:
      containers:
      - name: ssl-app
        image: gcr.io/fifth-incentive-409919/ssl-app-release:ssl-app-release-1.0.3
        ports:
        - containerPort: 80